name: Quality Control

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  quality-control:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'

    - name: Install dependencies
      run: npm ci

    - name: Run ESLint
      uses: actions/eslint@v5
      with:
        eslint-config: 'airbnb'
        working-directory: ./src
        args: . --ext .js
      env:
        NODE_OPTIONS: --max-old-space-size=4096

    - name: Run Stylelint
      uses: actions/stylelint@0.5.0
      with:
        config-path: .stylelintrc.json
        files: 'src/**/*.css'

    - name: Run HTMLHint
      uses: actions/htmlhint@v2
      with:
        files: 'src/**/*.html'
