name: Automatically test W3C validation, handicap accessibility
# I already have a javascript style checking in quality controling using Eslint
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  w3c-validation:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install
          npm install axe-webdriverjs

      - name: Starting Web Server
        run: npm start &

      - name: W3C validation
        run: npx html-validate http://localhost:3000 --format=checkstyle . > ./test-results/W3C-validation-report.xml || true

      - name: Handicap Accessibility Validation
        run: npx axe-webdriverjs http://localhost:3000 --headless --save ./test-results/handicap_accessibility.json || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: test-results/


