name: Automatically test W3C validation, handicap accessibility
# I already have a javascript style checking in quality controling using Eslint
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  w3c-validation:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Install dependencies
          run: sudo apt-get update && sudo apt-get install -y w3c-markup-validator
        - name: Validate HTML with W3C validator
          run: |
            find . -name "*.html" -type f -print0 | xargs -0 -n1 -P8 validate -e utf-8

  # axe-core:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2
  #     - name: Install dependencies
  #       run: npm install
  #     - name: Test accessibility with Axe Core
  #       uses: https://github.com/dequelabs/axe-core
  #       with:
  #         url: ${{ env.URL }}
          